### ISSUE TITLE
Inconsistent casing on context menu

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#135]
![screen shot 2015-04-24 at 02 57 22](https://cloud.githubusercontent.com/assets/667194/7311022/c0039d78-ea2d-11e4-8d26-436594785bc0.png)

**Comment by ctolkien** [comment]
This is fixed, not where when!

**Comment by nosami** [comment]
![screen shot 2015-04-28 at 12 27 26](https://cloud.githubusercontent.com/assets/667194/7368646/17d04c82-eda2-11e4-81ce-deb2b43001fc.png)

It isn't fixed
