### ISSUE TITLE
Uncaught TypeError: Cannot read property 'makeRequest' of null

### ISSUE THREAD

**Issue by douglasstarnes** [OmniSharp/omnisharp-atom#301]
I upgraded to 0.4.33 to address #253 and #276.  Those appear to be fixed but now there is a new problem.  I've only tried it on Linux so far.  The Omnisharp output is not throwing errors this time.

1. Finish a statement by typing a semicolon

**Atom Version**: 0.199.0
**System**: linux 3.13.0-52-generic
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.33

### Stack Trace

Uncaught TypeError: Cannot read property 'makeRequest' of null

```
At /home/userhome/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:37

TypeError: Cannot read property 'makeRequest' of null
  at Function.Omni.makeRequest (/home/userhome/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:37:50)
  at CodeFormat.formatOnKeystroke (/home/userhome/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-format.ts:27:32)
  at atom-workspace.<anonymous> (/home/userhome/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-format.ts:20:120)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:42.3.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -0:34.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:31.5.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:28 core:undo (atom-text-editor.editor.is-focused)
     -0:25.3.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:21.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:18.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:14.7.0 omnisharp-atom:intellisense-space (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.7.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
 22x -0:13 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:10.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:10.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:10.2.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:04.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:00.7.0 omnisharp-atom:code-format-on-semicolon (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
linter, v0.12.2
omnisharp-atom, v0.4.33

# Dev
No dev packages
```

**Comment by nosami** [comment]
Should be fixed in v0.5.0.

**Comment by VitorBarbosa** [comment]
I'm still getting this same error, but when I try to format code.

[Enter steps to reproduce below:]

1. Open a .cs file
2. Press the Code Format shortcut ( Ctrl+K, Ctrl+D )

**Atom Version**: 0.199.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.5.3


### Stack Trace

Uncaught TypeError: Cannot read property 'makeRequest' of null

```
At ...\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni.js:39

TypeError: Cannot read property 'makeRequest' of null
  at Function.Omni.makeRequest (...\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni.js:39:22)
  at ...\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\code-format.ts:13:36
  at atom-text-editor.<anonymous> (...\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:75:17)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (...\AppData\Local\atom\app-0.199.0\resources\app.asar\src\command-registry.js:238:29)
  at ...\AppData\Local\atom\app-0.199.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (...\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (...\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (...\AppData\Local\atom\app-0.199.0\resources\app.asar\src\window-event-handler.js:178:20)

```

### Commands

```
     -1:20.1.0 core:paste (atom-text-editor.editor.is-focused)
     -1:18.6.0 editor:select-line (atom-text-editor.editor.is-focused)
     -1:16.5.0 grammar-selector:show (atom-text-editor.editor.is-focused)
  3x -1:14.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:14 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:12.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:12.1.0 omnisharp-atom:code-format (atom-text-editor.editor.is-focused)
     -0:34 core:save-as (atom-text-editor.editor.is-focused)
     -0:22.4.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:21.7.0 omnisharp-atom:code-format (atom-text-editor.editor.is-focused)
     -0:09.8.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:05.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:05.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:03.3.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:02.8.0 omnisharp-atom:code-format (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "fileEncoding": "windows1252",
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
linter, v0.12.3
omnisharp-atom, v0.5.3

# Dev
No dev packages
```

**Comment by willslytech** [comment]
Still getting error says Atom is up to date but Omnisharp still not catching error shutting down when trying to put semi-colon after system;

**Comment by douglasstarnes** [comment]
I'm not seeing the error but it appears that Omnisharp has exited the building so that might be why.  This is on Atom 0.200 which updated earlier today it seems.

**Comment by willslytech** [comment]
Awesome can't wait thanks

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On Wed, May 20, 2015 at 1:18 AM, OmniSharp/omnisharp-atom
<reply@reply.github.com>
wrote:
I'm not seeing the error but it appears that Omnisharp has exited the building
so that might be why. This is on Atom 0.200 which updated earlier today it
seems.

—
Reply to this email directly or view it on GitHub
[https://github.com/OmniSharp/omnisharp-atom/issues/301#issuecomment-103763313] .[https://github.com/notifications/beacon/ALRt79FnEB0Mx_lnJwXXLtLPW-OB9foGks5oLBCygaJpZM4Eduvc.gif]

**Comment by nosami** [comment]
I can't reproduce this. I have no idea where to start :(

**Comment by douglasstarnes** [comment]
I don't get an error, but I don't see the flame icon in the status bar nor is there a menu for OmniSharp yet it is installed.  So I can only assume that it sliently bailed.  Thus I can't get a stack trace.  I have only tried this on OS X.  Will confirm on Linux later.

**Comment by ctolkien** [comment]
@douglasstarnes If the flame icon isn't appearing then the plugin hasn't been loaded appropriately via atom. There might be some simple debug info in the console if you bring up the dev tools.

**Comment by nosami** [comment]
Try `rm -rf ~/.atom/packages/omnisharp-atom` and reinstalling.

**Comment by nosami** [comment]
This should be fixed in v0.6.5

**Comment by douglasstarnes** [comment]
Same error, different file. :( 


1. Terminate a C# statement by typing a semicolon

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.6.5


### Stack Trace

Uncaught TypeError: Cannot read property 'makeRequest' of undefined

```
At /Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

TypeError: Cannot read property 'makeRequest' of undefined
  at AnonymousObserver._onNext (/Users/userhome/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-format.js:33:37)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1962:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1894:35)
  at AnonymousObserver.tryCatcher (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1894:35)
  at scheduleItem (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2915:16)
  at Scheduler.scheduleNow [as _schedule] (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1226:50)
  at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:970:19)
  at JustSink.run (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2920:36)
  at JustObservable.subscribeCore (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2905:19)
  at JustObservable.tryCatcher (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at [object Object].setDisposable [as action] (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2208:46)
  at [object Object].ScheduledItem.invokeCore (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:929:17)
  at [object Object].ScheduledItem.invoke (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:917:40)
  at runTrampoline (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1239:37)
  at tryCatcher (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at Scheduler.scheduleNow [as _schedule] (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1250:45)
  at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:970:19)
  at JustObservable.subscribe (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2220:32)
  at JustObservable.Observable._subscribe (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2143:28)
  at JustObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/userhome/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2160:19)
  at CodeFormat.formatOnKeystroke (/Users/userhome/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-format.js:32:54)
  at /Users/userhome/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-format.js:25:109
  at atom-text-editor.<anonymous> (/Users/userhome/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:84:17)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -1:23.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:12.6.0 application:open (atom-text-editor.editor.is-focused)
  3x -1:06.2.0 omnisharp-atom:toggle-output (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:55.7.0 omnisharp-atom:toggle (a.omnisharp-atom-button)
  2x -0:41.6.0 omnisharp-atom:toggle-output (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:36.8.0 omnisharp-atom:find-usages (a.omnisharp-atom-button)
  3x -0:22.3.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:14.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.6.0 omnisharp-atom:code-format-on-semicolon (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v4.5.0
atom-yeoman, v0.2.0
file-icons, v1.5.5
language-elixir, v0.4.0
language-fsharp, v0.8.4
language-rust, v0.4.3
linter, v0.12.6
omnisharp-atom, v0.6.5

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
@douglasstarnes any chance you would mind trying this out with 0.9.1?

**Comment by douglasstarnes** [comment]
@david-driscoll Sure David.  I'll try it out tomrrow and let you know.

**Comment by david-driscoll** [comment]
Closing, I think we have this one solved now!
