### ISSUE TITLE
Uncaught Error: spawn mono ENOENT

### ISSUE THREAD

**Issue by elleryfamilia** [OmniSharp/omnisharp-atom#42]
I've installed all the pieces successfully, yet when I open up a .cs file and start omnisharp, I get this error:

![screen shot 2014-12-08 at 2 38 16 am](https://cloud.githubusercontent.com/assets/55049/5336031/4f23c51c-7e83-11e4-831e-6e880852426d.png)

Running KRE 1.0.0-beta1

**Comment by elleryfamilia** [comment]
@louispellerin Were you ever able to get this working on your machine?

**Comment by louispellerin** [comment]
I haven't had much time to play with this, but I've just updated Atom and found no updates to omni-sharp. The bug is still there.

**Comment by nosami** [comment]
Where is mono installed to on your machine? Any chance that the path contains spaces?

**Comment by elleryfamilia** [comment]
Interestingly enough, it started working for me on it's own. I'm running Atom 0.165.0 with Omnisharp 0.1.6

**Comment by louispellerin** [comment]
I assume it was installed here: /Users/lpellerin/.kre/packages/KRE-Mono.1.0.0-beta1/bin

Thing is, I just followed the Getting Started guide (https://github.com/aspnet/home#getting-started). I used homebrew to install everything.

**Comment by louispellerin** [comment]
The latest version of Atom (0.168) now gives me the following error:
'mono' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

However, after running kvm upgrade, I get this:
Determining latest version
Latest version is 1.0.0-beta1
KRE-Mono.1.0.0-beta1 already installed.
Adding /Users/lpellerin/.kre/packages/KRE-Mono.1.0.0-beta1/bin to process PATH
Updating alias 'default' to 'KRE-Mono.1.0.0-beta1'

**Comment by eskalation** [comment]
I have the same issue. Atom 0.169, Mono 3.10.0.

Mono was installed using homebrew.

**Comment by sgratwohl** [comment]
had the same problem. mono and atom installed by brew. if i start atom from the launchpad and try to start omnisharp i get this error: "'mono' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process."

however if i start atom from the console i can start omnisharp. 

i have no clue of brew and not much of macos in general so i don't know know what the difference is.

**Comment by michaelblyons** [comment]
Echoing @eskalation:

```bash
$ which mono
/usr/local/bin/mono
$ mono --version
Mono JIT compiler version 3.10.0 (tarball Wed Oct 22 10:06:03 BST 2014)
```
but attempting to fire up the _O#_ server in Atom tells me the following:
> Starting Omnisharp server `(pid:undefined, port:55507)`
> `mono` could not be found, please ensure it is installed and in your path

OSX Yosemite

**Comment by nosami** [comment]
Try starting Atom from the terminal and report back. This way the PATH variable will be inherited.

**Comment by michaelblyons** [comment]
@nosami That worked for me. OmniSharp for Sublime seems to have [explicitly added `/usr/local/bin`](https://github.com/OmniSharp/omnisharp-sublime/commit/9b9b85cff954550c85109b65733e067762bb0366) for those of us using HomeBrew.

**Comment by nosami** [comment]
Yeah... looks like omnisharp-atom should do the same thing.

**Comment by michaelblyons** [comment]
The error no longer occurs from me. No need for launch from terminal. With no evidence to support it, I suspect **0.193.0**

**Comment by nosami** [comment]
Yes... this was fixed. Thanks for reporting.

**Comment by david-driscoll** [comment]
@elleryfamilia @louispellerin @eskalation @sgratwohl are ya'll still having this problem?

**Comment by elleryfamilia** [comment]
@david-driscoll Nope... hasn't occurred for me. Not sure which version fixed it though.

**Comment by louispellerin** [comment]
looks fixed.

**Comment by sgratwohl** [comment]
looks fixed for me too

**Comment by thomasnelson4** [comment]
Using OSX El Capitan and Atom 1.0.2, I am getting this same error **UNLESS** I open Atom from the terminal. Using Mono 4.0.2

Mono is in my PATH, however I had to add 'source ~/.bashrc' to my ~/.profile to be able to access mono from terminal.

**Comment by aggieben** [comment]
I am experiencing this issue with Atom 1.7.3 and omnisharp-atom 0.29.3.
